MinistryApp/Controllers/NewsEventController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Ministry.Models;
using MinistryApp.Models;
using System.IO;
using System.Threading.Tasks;
using System;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace Ministry.Controllers
{
    public class NewsEventController : Controller
    {
        private readonly MinistryDBContext _context;
        private IWebHostEnvironment _webHostEnvironment;
        public IConfiguration _configuration;


        public NewsEventController(MinistryDBContext context, IWebHostEnvironment webHostEnvironment, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.NewsEventList.ToListAsync());
        }
        public async Task<IActionResult> ViewNews()
        {
            return View(await _context.NewsEventList.Where(e => e.IsActive == true).ToListAsync());
        }

        // GET: Flat/Create
        public IActionResult AddOrEdit(int id = 0)
        {

            if (id == 0)
                return View(new NewsEventsVM());
            else
                return View(_context.NewsEventList.Find(id));
        }

        // POST: Employee/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(NewsEventsVM Obj)
        {
            string uniqueFileName = string.Empty;


            try
            {
                try
                {
                    uniqueFileName = GetUniqueFileName(Obj.Image.FileName);
                    var dir = Path.Combine(_webHostEnvironment.WebRootPath, "assets/news_image");
                    if (!Directory.Exists(dir))
                    {
                        Directory.CreateDirectory(dir);
                    }
                    var filePath = Path.Combine(dir, uniqueFileName);
                    await Obj.Image.CopyToAsync(new FileStream(filePath, FileMode.Create));
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                }
                Obj.ImageName = uniqueFileName;

                //if (ModelState.IsValid)
                //{
                if (Obj.Id == 0)
                    _context.Add(Obj);
                else
                    _context.Update(Obj);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                //}
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }

            return View(Obj);
        }

        private string GetUniqueFileName(string fileName)
        {
            fileName = Path.GetFileName(fileName);
            return Path.GetFileNameWithoutExtension(fileName)
                   + "_"
                   + Guid.NewGuid().ToString().Substring(0, 4)
                   + Path.GetExtension(fileName);
        }



        // GET: Employee/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var valObj = await _context.NewsEventList.FindAsync(id);
            _context.NewsEventList.Remove(valObj);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

MinistryApp/Views/NewsEvent/AddOrEdit.cshtml
@using Ministry.Models;
@model Ministry.Models.NewsEventsVM
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    ViewData["Title"] = @localizer["Create"];
}

<h4>@localizer["Create/Edit"]</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit" enctype="multipart/form-data" method="post">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-row">
                <div class="form-group  col-md-6">
                    <label asp-for="LanguageType" class="control-label"></label>
                    <select asp-for="LanguageType" asp-items="Html.GetEnumSelectList<LanguageType>()">
                        <option selected="selected" value="">Select Language</option>
                    </select>
                    <span asp-validation-for="LanguageType" class="text-danger"></span>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group  col-md-6">
                    <label asp-for="NewsTitle" class="control-label"></label>
                    @Html.TextBoxFor(m => m.NewsTitle, new { @class = "form-control", @maxlength = "35" })
                    <span asp-validation-for="NewsTitle" class="text-danger"></span>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group  col-md-6">
                    <label asp-for="NewsDescription" class="control-label"></label>
                    @Html.TextAreaFor(m => m.NewsDescription, new { @class = "form-control", @maxlength = "500" })
                    <span asp-validation-for="NewsDescription" class="text-danger"></span>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <label for="ImageFile">Image</label>
                    <input class="form-control" type="file" id="Image" name="Image" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group">
                    <label for="IsActive">Active</label>
                    @Html.CheckBoxFor(model => model.IsActive, new { @class = "cIsRate form-control " })
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <input type="submit" value="@localizer["Submit"]" class="btn btn-primary btn-block" />
                </div>
                <div class="form-group col-md-6">
                    <a asp-action="Index" class="btn btn-secondary btn-block"><i class="fa fa-table"></i>@localizer["Back to List"]</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MinistryApp/Views/NewsEvent/Index.cshtml
@model IEnumerable<Ministry.Models.NewsEventsVM>

@{
    ViewData["Title"] = "Index";
}

<h4>News/Event List</h4>
<hr />
<div class="form-group col-md-6">
    <a asp-action="Index" asp-controller="NewsEvent" class="btn btn-secondary btn-block"><i class="fa fa-table"></i>News/Event</a>
</div>


<br />
<table class="table table-hover" id="datatable">
    <thead>
        <tr style="background-color: #f7ecfd">
            <th>
                Sl.
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NewsTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NewsDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th>
                <a asp-action="AddOrEdit" class="btn btn-outline-success"><i class="far fa fa-plus-square"></i>Create New</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            int rowNo = 0;
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @{
                        rowNo++;
                    } @rowNo
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NewsTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NewsDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublishDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsActive)
                </td>
                <td>
                    <a asp-action="AddOrEdit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="text-danger ml-1" onclick="return confirm('Are you sure to delete this record?')">Delete</a>
                </td>
            </tr>
        }


    </tbody>
</table>

@section Scripts
    {
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.css" />

    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#datatable").DataTable();
        }
        )
    </script>
}

MinistryApp/Views/NewsEvent/ViewNews.cshtml
@model IEnumerable<Ministry.Models.NewsEventsVM>

<section class="inner-page">
    <div class="container">
        @for(int i=0;i<= 2; i++)
        {
            <div class="row">
            @foreach (var item in Model)
            { 
                
                
            <div class="col-lg-4">
                <div class="card">
                    <img class="card-img-top" src="../assets/news_image/@item.ImageName" alt="news">
                    <div class="card-body">
                        <h5 class="card-title">@item.NewsTitle</h5>
                        <p class="card-text">@item.NewsDescription</p>
                        <a href="news-detail.html" class="btn btn-primary">Read more...</a>
                    </div>

                </div>
            </div>


                    @if (i == 2)
                        break;
                }
            </div>
            break;
        }
    </div>
</section>