MinistryApp/Controllers/FileModelController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ministry.Models;
using MinistryApp.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Ministry.Controllers
{
    public class FileModelController : Controller
    {

        private readonly MinistryDBContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;
        public FileModelController(MinistryDBContext context, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: Flat
        public IActionResult Index()
        {
            return View();
        }


        // GET: Flat
        public async Task<IActionResult> ListFilesRows()
        {
            return View(await _context.FilesList.Where(p => p.IsActive == true).ToListAsync());
        }

        // GET: Flat
        public IActionResult Dashboard()
        {
            return View();
        }


        public IActionResult OpenDummyData()
        {
            return View();
        }


        // GET: EnumValues/Create
        public IActionResult AddOrEdit(int id = 0)
        {
            var userName = User.FindFirstValue(ClaimTypes.Name);
            var categoryListObj = (from c in _context.FileCategoryList.Where(p => p.IsActive==true)
                                       select new SelectListItem()
                                       {
                                           Value = c.FileCategoryName.ToString(),
                                           Text = c.FileCategoryValue
                                       }).ToList();

            ViewBag.categoryList = categoryListObj;
            

            if (id == 0)
                return View(new FileModelVM());
            else
                return View(_context.FilesList.Find(id));
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(FileModelVM fileModelObj)
        {
            var userName = User.FindFirstValue(ClaimTypes.Name);
           

            ModelState.Clear();
            if (ModelState.IsValid)
            {
                if (fileModelObj.Id == 0)
                {

                    var GetChamberUserList = _context.Users
                                                .Where(p => p.UserRole== "Chamber" && p.IsActive == true)
                                                .Select(p => new { p.Id, p.UserName}).ToList();

                    foreach (var valStr in GetChamberUserList)
                    {
                        FileModelVM fileCreatedForChambersObj = new FileModelVM();
                        fileCreatedForChambersObj.ResonsiblePerson = valStr.UserName;

                        fileCreatedForChambersObj.FileCategory = fileModelObj.FileCategory;
                        fileCreatedForChambersObj.DateLine = fileModelObj.DateLine;
                        fileCreatedForChambersObj.CreatedBy = userName;
                        fileCreatedForChambersObj.CreatedDate = DateTime.Now;
                        fileCreatedForChambersObj.SubmitStatus = "Pending";
                        
                        fileCreatedForChambersObj.IsActive = true;
                        _context.Add(fileCreatedForChambersObj);
                    }



                    
                }
                
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(fileModelObj);
        }



        // GET: EnumValues/Create
        public IActionResult Details(int id = 0)
        {
            var userName = User.FindFirstValue(ClaimTypes.Name);
            var categoryListObj = (from c in _context.FileCategoryList.Where(p => p.IsActive == true)
                                   select new SelectListItem()
                                   {
                                       Value = c.FileCategoryName.ToString(),
                                       Text = c.FileCategoryValue
                                   }).ToList();

            ViewBag.categoryList = categoryListObj;


            if (id == 0)
                return View(new FileModelVM());
            else
                return View(_context.FilesList.Find(id));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(FileModelVM fileModelObj)
        {
            var userName = User.FindFirstValue(ClaimTypes.Name);


            ModelState.Clear();
            if (ModelState.IsValid)
            {
                if (fileModelObj.Id == 0)
                {

                    var GetChamberUserList = _context.Users
                                                .Where(p => p.UserRole == "Chamber" && p.IsActive == true)
                                                .Select(p => new { p.Id, p.UserName }).ToList();

                    foreach (var valStr in GetChamberUserList)
                    {
                        FileModelVM fileCreatedForChambersObj = new FileModelVM();
                        fileCreatedForChambersObj.ResonsiblePerson = valStr.UserName;

                        fileCreatedForChambersObj.FileCategory = fileModelObj.FileCategory;
                        fileCreatedForChambersObj.DateLine = fileModelObj.DateLine;
                        fileCreatedForChambersObj.CreatedBy = userName;
                        fileCreatedForChambersObj.CreatedDate = DateTime.Now;
                        fileCreatedForChambersObj.SubmitStatus = "Pending";

                        fileCreatedForChambersObj.IsActive = true;
                        _context.Add(fileCreatedForChambersObj);
                    }




                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(fileModelObj);
        }

        // GET: EnumValues/Create
        public IActionResult FileDetails(int id = 0)
        {
            return View();
        }


            // GET: Employee/Delete/5
            public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var values = await _context.FilesList.FindAsync(id);
            values.IsActive = false;

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult DownloadFile(string filePath)
        {

            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);
            string fileName = "myfile.pdf";
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);

            //For preview pdf and the download it use below code
            // var stream = new FileStream(filePath, FileMode.Open);
            //return new FileStreamResult(stream, "application/pdf");
        }

    }
}

MinistryApp/Views/FileModel/AddOrEdit.cshtml
@model Ministry.Models.FileModelVM

@{
    ViewData["Title"] = "Create";
}


<h4>Create</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form name="form1" asp-action="AddOrEdit" asp-controller="FileModel" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(m => m.Id)
        <div class="form-group col-md-12">
            
                <label asp-for="FileCategory" class="control-label"></label>
                @Html.DropDownListFor(m => m.FileCategory, new SelectList(ViewBag.categoryList, "Value", "Text"), "Select File Category", new { @class = "form-control" })
                <span asp-validation-for="FileCategory" class="text-danger"></span>
            
        </div>

            <div class="form-row">
                <div class="form-group col-md-12">
                    <label asp-for="DateLine" class="control-label"></label>
                    <input asp-for="DateLine" id="datepicker" type="text" class="form-control" />
                    <span asp-validation-for="DateLine" class="text-danger"></span>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <input type="submit" value="Submit" class="btn btn-primary btn-block" /> @*onclick="phonenumber(document.form1.Mobile)"*@
                </div>
                <div class="form-group col-md-6">
                    <a asp-action="Index" class="btn btn-secondary btn-block"><i class="fa fa-table"></i>Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#datepicker").datepicker();
        });
    </script>

}

MinistryApp/Views/FileModel/Dashboard.cshtml
@model IEnumerable<Ministry.Models.FileModelVM>

@{
    ViewData["Title"] = "Index";
}
<style>
    .card {
        background-color: #fff;
        border-radius: 10px;
        border: none;
        position: relative;
        margin-bottom: 30px;
        box-shadow: 0 0.46875rem 2.1875rem rgba(90,97,105,0.1), 0 0.9375rem 1.40625rem rgba(90,97,105,0.1), 0 0.25rem 0.53125rem rgba(90,97,105,0.12), 0 0.125rem 0.1875rem rgba(90,97,105,0.1);
    }

        .card:hover {
            background: #fff;
            box-shadow: 0px 15px 26px rgba(0, 0, 0, 0.50);
            /*-webkit-transition: all 0.2s ease-in;
        -moz-transition: all 0.2s ease-in;
        -ms-transition: all 0.2s ease-in;*/
            /* -o-transition: all 0.2s ease-in;
        transition: all 0.2s ease-in;*/
            /* margin-top: 50px;*/
        }


    .l-bg-cherry {
        background: linear-gradient(to right, #493240, #f09) !important;
        color: #fff;
    }

    .l-bg-blue-dark {
        background: linear-gradient(to right, #373b44, #4286f4) !important;
        color: #fff;
    }

    .l-bg-green-dark {
        background: linear-gradient(to right, #0a504a, #38ef7d) !important;
        color: #fff;
    }

    .l-bg-orange-dark {
        background: linear-gradient(to right, #a86008, #ffba56) !important;
        color: #fff;
    }

    .card .card-statistic-3 .card-icon-large .fas, .card .card-statistic-3 .card-icon-large .far, .card .card-statistic-3 .card-icon-large .fab, .card .card-statistic-3 .card-icon-large .fal {
        font-size: 110px;
    }

    .card .card-statistic-3 .card-icon {
        text-align: center;
        line-height: 50px;
        margin-left: 15px;
        color: #000;
        position: absolute;
        right: -5px;
        top: 20px;
        opacity: 0.1;
    }

    .l-bg-cyan {
        background: linear-gradient(135deg, #289cf5, #84c0ec) !important;
        color: #fff;
    }

    .l-bg-green {
        background: linear-gradient(135deg, #23bdb8 0%, #43e794 100%) !important;
        color: #fff;
    }

    .l-bg-orange {
        background: linear-gradient(to right, #f9900e, #ffba56) !important;
        color: #fff;
    }

    .l-bg-cyan {
        background: linear-gradient(135deg, #289cf5, #84c0ec) !important;
        color: #fff;
    }
</style>

<h1>List</h1>
<hr />
<a class="btn btn-primary" style="width:auto"
   asp-controller="FAQ" asp-action="index">
    FAQ
</a>

<a class="btn btn-primary" style="width:auto"
   asp-controller="FileCategory" asp-action="index">
    Category
</a>

<a asp-action="Register" asp-controller="Account"
   class="btn btn-outline-success" style="width:auto">
    <i class="far fa-plus-square"></i>Add Chamber
</a>


<a asp-action="Index" asp-controller="Chamber"
   class="btn btn-outline-success" style="width:auto">
    <i class="far fa-plus-square"></i>Chamber Dashboard
</a>

<a asp-action="SuperUserRegister" asp-controller="Account"
   class="btn btn-outline-success" style="width:auto">
    <i class="far fa-plus-square"></i>Add Admin
</a>


<br />
<a asp-action="ListFilesRows" asp-controller="FileModel"
   class="btn btn-outline-success" style="width:auto">
    <i class="far fa-plus-square"></i>Files
</a>

<br />

<div class="form-row">

    <div class="form-group col-md-4">
        <div class="card" style="width: auto;">
            <div class="card-body" style="background-color: #f7ecfd">
                <div class="row g-0">
                    <div class="col-md-8">
                        <h5 class="card-title">metropolitan chamber of commerce and industry</h5>
                        <h6 class="card-subtitle mb-2 text-muted">7</h6>
                        <p class="card-text">&nbsp</p>
                        <a href="/FileModel/OpenDummyData" class="btn btn-primary">More</a>
                    </div>
                    <div class="col-md-4">
                        @*<img src="~/../assets/icons/Renewal.png" class="img-fluid rounded-start" alt="Bill">*@
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="form-group col-md-4">
        <div class="card" style="width: auto;">
            <div class="card-body" style="background-color: #f7ecfd">
                <div class="row g-0">
                    <div class="col-md-8">
                        <h5 class="card-title">Bangladesh Women Chamber of Commerce and Industry</h5>
                        <h6 class="card-subtitle mb-2 text-muted">18</h6>
                        <p class="card-text"></p>
                        @*<a href="/Report/Meeting?fromDate=@fromDate&toDate=@toDate" class="btn btn-primary">@localizer["Details"]</a>*@
                    </div>
                    <div class="col-md-4">
                        @*<img src="~/../assets/icons/Meeting-2.png" class="img-fluid rounded-start" alt="Bill">*@
                    </div>
                </div>
            </div>
        </div>
    </div>




    <div class="form-group col-md-4">
        <div class="card" style="width: auto;">
            <div class="card-body" style="background-color: #f7ecfd">
                <div class="row g-0">
                    <div class="col-md-8">
                        <h5 class="card-title">zella chamber of commerce industry</h5>
                        <h6 class="card-subtitle mb-2 text-muted">68</h6>
                        <p class="card-text">&nbsp;</p>
                        @*<a href="/Report/PendingTask?fromDate=@fromDate&toDate=@toDate" class="btn btn-primary">@localizer["Details"]</a>*@
                    </div>
                    <div class="col-md-4">
                        @*<img src="~/../assets/icons/Pending.png" class="img-fluid rounded-start" alt="Bill">*@
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>

<div class="form-row">

    <div class="form-group col-md-4">
        <div class="card" style="width: auto;">
            <div class="card-body" style="background-color: #f7ecfd">
                <div class="row g-0">
                    <div class="col-md-8">
                        <h5 class="card-title">Joutho chamber of commerce industry</h5>
                        <h6 class="card-subtitle mb-2 text-muted">36</h6>
                        <p class="card-text">&nbsp</p>
                        @*<a href="/Report/Renewal?fromDate=s&toDate=s" class="btn btn-primary">More</a>*@
                    </div>
                    <div class="col-md-4">
                        @*<img src="~/../assets/icons/Renewal.png" class="img-fluid rounded-start" alt="Bill">*@
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="form-group col-md-4">
        <div class="card" style="width: auto;">
            <div class="card-body" style="background-color: #f7ecfd">
                <div class="row g-0">
                    <div class="col-md-8">
                        <h5 class="card-title">upozella chamber</h5>
                        <h6 class="card-subtitle mb-2 text-muted">2</h6>
                        <p class="card-text"></p>
                        @*<a href="/Report/Meeting?fromDate=@fromDate&toDate=@toDate" class="btn btn-primary">@localizer["Details"]</a>*@
                    </div>
                    <div class="col-md-4">
                        @*<img src="~/../assets/icons/Meeting-2.png" class="img-fluid rounded-start" alt="Bill">*@
                    </div>
                </div>
            </div>
        </div>
    </div>




    <div class="form-group col-md-4">
        <div class="card" style="width: auto;">
            <div class="card-body" style="background-color: #f7ecfd">
                <div class="row g-0">
                    <div class="col-md-8">
                        <h5 class="card-title">পেশা জীবি গ্রুপ মালিক</h5>
                        <h6 class="card-subtitle mb-2 text-muted">187</h6>
                        <p class="card-text">&nbsp;</p>
                        @*<a href="/Report/PendingTask?fromDate=@fromDate&toDate=@toDate" class="btn btn-primary">@localizer["Details"]</a>*@
                    </div>
                    <div class="col-md-4">
                        @*<img src="~/../assets/icons/Pending.png" class="img-fluid rounded-start" alt="Bill">*@
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>





@section Scripts
{


}

MinistryApp/Views/FileModel/Details.cshtml
@model Ministry.Models.FileModelVM

@{
    ViewData["Title"] = "Create";
}


<h4>Details</h4>
<hr />
<div class="row">
    <div class="col-md-12">
                <form asp-action="AddOrEdit" enctype="multipart/form-data" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    @Html.HiddenFor(m => m.Id)
                    @Html.HiddenFor(m => m.Attachment)


                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label asp-for="FileCategory" class="control-label"></label>

                            @Html.TextBoxFor(model => model.FileCategory, new { @placeholder = "FileCategory", @class = "cCode form-control", @readonly = "readonly" })
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label asp-for="DateLine" class="control-label"></label>

                            @Html.TextBoxFor(model => model.DateLine, new { @placeholder = "DateLine", @class = "cCode form-control", @readonly = "readonly" })
                        </div>
                    </div>


                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label asp-for="SubmitStatus" class="control-label"></label>

                            @Html.TextBoxFor(model => model.SubmitStatus, new { @placeholder = "SubmitStatus", @class = "cCode form-control", @readonly = "readonly" })
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label asp-for="CreatedBy" class="control-label"></label>

                            @Html.TextBoxFor(model => model.CreatedBy, new { @placeholder = "CreatedBy", @class = "cCode form-control", @readonly = "readonly" })
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-12" style="vertical-align:bottom">
                            @Html.LabelFor(model => model.Attachment, new { @class = "attachment" })
                            
                            <div id="fileContent" style="display:block;" class="form-group col-md-12">
                                @if (Model.Attachment != null && Model.Attachment != "")
                                {
                                    <div class="col-md-6" id="fileExist">
                                        @Html.LabelFor(model => model.Attachment, new { @class = "FileUpload" })
                                        @Html.HiddenFor(model => model.Attachment);
                                        <div class="col-md-6">
                                            <a class="" target="_blank" href="~/Files/@Model.Attachment">
                                                <img class="attachment" src="~/../assets/icons/files.png" width="30" alt="File" title="File" accept="application/pdf, application/vnd.ms-excel" />
                                            </a>

                                            <span onclick="FileDeleteThis(this);" data-id="@Model.Id" data-table="501" data-field="Attachment" data-url="@Model.Attachment">
                                                <img class="attachment" src="~/../assets/img/document_delete.png" width="30" alt="File" title="File" />
                                            </span>
                                        </div>
                                    </div>

                                    <div class="col-md-12">

                                    </div>


                                    try
                                    {

                                    }
                                    catch
                                    {
                                        <span>File exists but Not Found...</span>
                                    }





                                }
                                else
                                {

                                }
                            </div>
                        </div>
                    </div>



            <div class="form-row">                
                <div class="form-group col-md-12">
                    <a asp-action="Index" class="btn btn-secondary btn-block"><i class="fa fa-table"></i>Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>

MinistryApp/Views/FileModel/FileDetails.cshtml
<h1>Hello PAGE</h1>

MinistryApp/Views/FileModel/ListFilesRows.cshtml
@model IEnumerable<Ministry.Models.FileModelVM>

@{
    ViewData["Title"] = "List";
}
<style>
    .red {
        background-color: red;
    }

    .green {
        background-color: green;
    }

    .yellow {
        background-color: yellow;
    }
</style>

<h1>List</h1>
<hr />
@*<a class="btn btn-primary" style="width:auto"
   asp-controller="FAQ" asp-action="index">
    FAQ
</a>

<a class="btn btn-primary" style="width:auto"
   asp-controller="FileCategory" asp-action="index">
    Category
</a>

<a asp-action="Register" asp-controller="Account"
   class="btn btn-outline-success" style="width:auto">
    <i class="far fa-plus-square"></i>Add Chamber
</a>

<a asp-action="SuperUserRegister" asp-controller="Account"
   class="btn btn-outline-success" style="width:auto">
    <i class="far fa-plus-square"></i>Add Admin
</a>*@


<br />
<table class="table table-hover" id="filedatatable">
    <thead>
        <tr style="background-color: #f7ecfd">
            <th>
                SL.
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileCategory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ResonsiblePerson)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubmitStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateLine)
            </th>
            <th>
                Download
            </th>
            <th>

                <a asp-action="AddOrEdit" class="btn btn-outline-success"><i class="far fa fa-plus-square"></i>New</a>

            </th>
        </tr>
    </thead>
    <tbody>
        @{ int rowNo = 0; }
        @foreach (var item in Model)
        {
            var rowColor = "";
            if (item.SubmitStatus == "Submitted")
            {
                rowColor = "#7ff748";
            }
            else if (item.SubmitStatus == "Pending")
            {
                rowColor = "#fcda5d";
            }

            if (item.SubmitStatus == "Pending" && item.DateLine <= DateTime.Now)
            {
                rowColor = "#fa5c6a";
            }



            <tr style="background-color:@rowColor">
                <td>
                    @{rowNo++;} @rowNo
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FileCategory)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ResonsiblePerson)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubmitStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateLine)
                </td>
                <td>
                    @if (item.Attachment != null && item.Attachment != "")
                    {
                        try
                        {
                            <div class="col-md-6" id="fileExist">
                                @*@Html.LabelFor(model => item.Attachment, new { @class = "FileUpload" })*@
                                @Html.HiddenFor(model => item.Attachment)
                                <div class="col-md-6">
                                    <a class="" target="_blank" href="~/Files/@item.Attachment">
                                        <img class="attachment" src="~/../assets/icons/files.png" width="30" alt="File" title="File" accept="application/pdf, application/vnd.ms-excel" />
                                    </a>
                                </div>
                            </div>

                        }
                        catch
                        {
                            <span>File exists but Not Found...</span>
                        }
                    }
                    else
                    {
                        <span>File Not Found...</span>
                    }


                    @*<a asp-action="DownloadFile" asp-route-filePath="@item.FilePath">Download</a>*@
                </td>
                <td>

                    <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                    @*<a asp-action="AddOrEdit" asp-route-id="@item.Id"><i class="fas fa-marker fa-lg"></i></a>*@
                    <a asp-action="Delete" asp-route-id="@item.Id" class="text-danger ml-1" onclick="return confirm('Are you sure to delete this record?')"><i class="fas fa-trash-alt fa-lg"></i></a>
                </td>
            </tr>
        }


    </tbody>
</table>

@section Scripts
{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.css" />

    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#filedatatable").DataTable();
        }
        )
    </script>
}

MinistryApp/Views/FileModel/OpenDummyData.cshtml
<table class="table table-hover">
    <thead>
        <tr style="background-color: #f7ecfd">
            <th>
                SL.
            </th>
            <th>
                Name
            </th>
        </tr>
    </thead>
    <tbody>

        <tr>
            <td>
                1
            </td>
            <td>
                Dhaka
            </td>
        </tr>

        <tr>
            <td>
                2
            </td>
            <td>
                Sylhet
            </td>
        </tr>


        <tr>
            <td>
                3
            </td>
            <td>
                Chattogram
            </td>
        </tr>

        <tr>
            <td>
                4
            </td>
            <td>
                Ranpur
            </td>
        </tr>

        <tr>
            <td>
                5
            </td>
            <td>
                Barishal
            </td>
        </tr>

        <tr>
            <td>
                6
            </td>
            <td>
                Mymensingh
            </td>
        </tr>

        <tr>
            <td>
                7
            </td>
            <td>
                Gazipur
            </td>
        </tr>


    </tbody>
</table>

@section Scripts
{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.css" />

    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#filedatatable").DataTable();
        }
        )
    </script>
}