MinistryApp/Controllers/ELearningController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Ministry.Models;
using MinistryApp.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Ministry.Controllers
{
    public class ELearningController : Controller
    {
        private readonly MinistryDBContext _context;
        private IWebHostEnvironment _webHostEnvironment;
        public IConfiguration _configuration;


        public ELearningController(MinistryDBContext context, IWebHostEnvironment webHostEnvironment, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.ELearningList.ToListAsync());
        }


        public async Task<IActionResult> ELearningView()
        {
            return View(await _context.ELearningList.Where(e=>e.IsActive==true).ToListAsync());
        }




        // GET: Flat/Create
        public IActionResult AddOrEdit(int id = 0)
        {

            if (id == 0)
                return View(new ELearningVM());
            else
                return View(_context.ELearningList.Find(id));
        }



        // POST: Employee/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(ELearningVM Obj)
        {
            string uniqueFileName = string.Empty;
            Obj.CreateDate = DateTime.Now;
            Obj.CreatedBy = User.Identity.Name != "" ? User.Identity.Name : "-";
            if (ModelState.IsValid)
            {
                try
                {
                    
                    if (Obj.Id == 0)
                        _context.Add(Obj);
                    else
                        _context.Update(Obj);

                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));

                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                }


                
            }
            return View(Obj);
        }


        // GET: Employee/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var valObj = await _context.ELearningList.FindAsync(id);
            _context.ELearningList.Remove(valObj);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

MinistryApp/Views/ELearning/AddOrEdit.cshtml
@using Ministry.Models;
@model Ministry.Models.ELearningVM
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    ViewData["Title"] = @localizer["Create"];
}

<h4>@localizer["Create/Edit"]</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-row">
                <div class="form-group  col-md-6">
                    <label asp-for="LanguageType" class="control-label"></label>
                    <select asp-for="LanguageType" asp-items="Html.GetEnumSelectList<LanguageType>()">
                        <option selected="selected" value="">Select Language</option>
                    </select>
                    <span asp-validation-for="LanguageType" class="text-danger"></span>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group  col-md-6">
                    <label asp-for="Title" class="control-label"></label>
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control", @maxlength = "35" })
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group  col-md-6">
                    <label asp-for="Description" class="control-label"></label>
                    @Html.TextAreaFor(m => m.Description, new { placeholder = "Please add description here" ,@class = "form-control"})
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group  col-md-6">
                    <label asp-for="VDOUrl" class="control-label"></label>
                    @Html.TextBoxFor(m => m.VDOUrl, new { @class = "form-control" })
                    <span asp-validation-for="VDOUrl" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group">
                    <label for="IsActive">Active</label>
                    @Html.CheckBoxFor(model => model.IsActive, new { @class = "cIsRate form-control " })
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <input type="submit" value="@localizer["Submit"]" class="btn btn-primary btn-block" />
                </div>
                <div class="form-group col-md-6">
                    <a asp-action="Index" class="btn btn-secondary btn-block"><i class="fa fa-table"></i>@localizer["Back to List"]</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MinistryApp/Views/ELearning/ELearningView.cshtml
@model IEnumerable<Ministry.Models.ELearningVM>


<section class="inner-page">
    <div class="container">

       @for(int i=0;i<= 1; i++)
        {
            <div class="row">
            @foreach (var item in Model)
            {            
                <div class="col-lg-6">
                    <div class="card">
                        <iframe width="100%" height="300" src="@item.VDOUrl" title="@item.Title" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                        <div class="card-body">
                                <h5 class="card-title"> @item.Title </h5>
                            <p class="card-text">@item.Description</p>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" style="width: 50%;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">50%</div><br />
                            </div>
                            <a href="detail-page.html" class="btn btn-success" style="margin-top:10px;">Resume Learning</a>
                        </div>
                    </div>
                </div>

                    @if (i == 1)
                        break;
            }
            </div> 
            break;
        }        

    </div>
</section>

MinistryApp/Views/ELearning/Index.cshtml
@model IEnumerable<Ministry.Models.ELearningVM>

@{
    ViewData["Title"] = "Index";
}

<h4>Elearning List</h4>
<hr />
<div class="form-group col-md-6">
    <a asp-action="Index" asp-controller="ELearning" class="btn btn-secondary btn-block"><i class="fa fa-table"></i>E-Learning</a>
</div>


<br />
<table class="table table-hover" id="datatable">
    <thead>
        <tr style="background-color: #f7ecfd">
            <th>
                Sl.
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LanguageType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VDOUrl)
            </th>
            <th>
                <a asp-action="AddOrEdit" class="btn btn-outline-success"><i class="far fa fa-plus-square"></i>Create New</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            int rowNo = 0;
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>@{
                        rowNo++;
                    } @rowNo</td>
                <td>
                    @Html.DisplayFor(modelItem => item.LanguageType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VDOUrl)
                </td>
                <td>                
                    <a asp-action="AddOrEdit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="text-danger ml-1" onclick="return confirm('Are you sure to delete this record?')">Delete</a>
                </td>
            </tr>
        }


    </tbody>
</table>

@section Scripts
    {
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.css" />

    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#datatable").DataTable();
        }
        )
    </script>
}